services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tea_mates
    ports:
      - "5432:5432"
    networks:
      - teaMates

networks:
  teaMates:
    driver: bridge
    name: teaMates
