spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      delivery-timeout: 5000ms # Fail after 5 seconds if Kafka is unreachable
      properties:
        request.timeout.ms: 3000  # Timeout a single request in 3s
        retry.backoff.ms: 1000    # Wait 1s before each retry
    template:
      observation-enabled: true
  datasource:
    url: jdbc:h2:mem:ordersdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      enabled: true

#  tracing:
#    sampling:
#      probability: 1.0
#
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces
