server:
  port: 8080

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:tea_mates
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none # Ensures tables are created before inserting data
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always  # Forces execution of data.sql on every restart
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      enabled: true

#  tracing:
#    sampling:
#      probability: 1.0
#
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces

#logging:
#  level:
#    software.amazon.awssdk.auth: DEBUG
#    io.awspring.cloud: DEBUG
