spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-processing-group
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate
