server:
  port: 8082

spring:
  application:
    name: order-processing-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-processing-group
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

  datasource:
    url: jdbc:h2:mem:orderprocessingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      enabled: true

#  tracing:
#    sampling:
#      probability: 1.0
#
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces
