services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"    # OTLP/HTTP
      - "4317:4317"    # OTLP/gRPC
    environment:
      - LOG_LEVEL=debug
    networks:
      - observer-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"  # Loki API
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    networks:
      - observer-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: always
    networks:
      - observer-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
    networks:
      - observer-net

volumes:
  grafana-data:

networks:
  observer-net:
    driver: bridge
    name: observer-net
