name: 🔥 Destroy TeaMates Infrastructure

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  destroy-infra:
    name: 🔥 Destroy Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .deployments/aws

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☁️ Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ap-southeast-1  # or reference a reusable input if needed

      - name: 🔄 Terraform Init
        run: terraform init

      - name: 🧨 Terraform Destroy
        run: terraform destroy -auto-approve
