name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS region (default: ap-southeast-1)"
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .deployments/aws
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☁️ Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ inputs.aws_region || secrets.AWS_REGION }}

      - name: ⚠️ Terraform Destroy
        run: terraform destroy -auto-approve
