on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        default: "ap-southeast-1"
      ecr_registry:
        type: string
        default: "376907302485.dkr.ecr.ap-southeast-1.amazonaws.com"
    secrets:
      OIDC_ROLE:
        required: true

jobs:
  provision-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .deployments/aws
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☁️ Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ inputs.aws_region }}

      - name: 🧪 Terraform Init
        run: terraform init

      - name: 📋 Terraform Plan
        run: terraform plan

      - name: 🚀 Terraform Apply
        run: terraform apply -auto-approve
